name: Docker Build and Push NGINX

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to github packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: checkout to target branch
        uses: actions/checkout@v2
      
      - name: Set repo owner and repo name in env vars
        env:
          REPO_OWNER_NAME: ${{ github.repository }}
        run: |
          REPO_OWNER=$(echo "$REPO_OWNER_NAME" | awk '$1=$1' FS="/" OFS=" " | awk '{ print $1}' | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV
          echo {{ env.REPO_OWNER }}
          REPO_NAME=$(echo "$REPO_OWNER_NAME" | awk '$1=$1' FS="/" OFS=" " | awk '{ print $2}')
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME"
    
      - name: Set released tag in env vars
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: pull nginx image
        run: docker pull nginx
      
      - name: build custom nginx image by renaming the official image
        run: docker tag nginx:latest ghcr.io/t2wil/nginx:${{ env.RELEASE_VERSION }}
      
        
      - name: Push to GitHub container registry
        run: |
          docker push ghcr.io/${{ env.REPO_OWNER }}/nginx:${{ env.RELEASE_VERSION }}
